"""Update MigraineEntry with daily fields

Revision ID: 79a3ee158a3a
Revises: cd45fc20c39f
Create Date: 2025-07-15 12:57:03.193389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a3ee158a3a'
down_revision: Union[str, Sequence[str], None] = 'cd45fc20c39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
