"""create migraine_entries table

Revision ID: 9caa1a1a23d2
Revises: de79d614ec03
Create Date: 2025-07-23 16:01:41.070325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caa1a1a23d2'
down_revision: Union[str, Sequence[str], None] = 'de79d614ec03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migraine_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sleep_duration', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('water_intake', sa.Float(), nullable=True),
    sa.Column('screen_time', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('bright_light', sa.Boolean(), nullable=True),
    sa.Column('irregular_meals', sa.Boolean(), nullable=True),
    sa.Column('weather_change', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migraine_entries_id'), 'migraine_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migraine_entries_id'), table_name='migraine_entries')
    op.drop_table('migraine_entries')
    # ### end Alembic commands ###
